; monochrome palette color ids
	const_def
	const SHADE_WHITE ; %00
	const SHADE_LIGHT ; %01
	const SHADE_DARK  ; %10
	const SHADE_BLACK ; %11
DEF NUM_PAL_COLORS EQU const_value

DEF PAL_COLOR_SIZE EQU 2
DEF PALETTE_SIZE EQU NUM_PAL_COLORS * PAL_COLOR_SIZE

DEF NUM_ACTIVE_PALS EQU 4

; pal/blk packets
; SetPalFunctions indexes (see engine/gfx/palettes.asm)
	const_def
	const SET_PAL_BATTLE_BLACK         ; $00
	const SET_PAL_BATTLE               ; $01
	const SET_PAL_TOWN_MAP             ; $02
	const SET_PAL_STATUS_SCREEN        ; $03
	const SET_PAL_POKEDEX              ; $04
	const SET_PAL_SLOTS                ; $05
	const SET_PAL_TITLE_SCREEN         ; $06
	const SET_PAL_NIDORINO_INTRO       ; $07
	const SET_PAL_GENERIC              ; $08
	const SET_PAL_OVERWORLD            ; $09
	const SET_PAL_PARTY_MENU           ; $0A
	const SET_PAL_POKEMON_WHOLE_SCREEN ; $0B
	const SET_PAL_GAME_FREAK_INTRO     ; $0C
	const SET_PAL_TRAINER_CARD         ; $0D

DEF SET_PAL_PARTY_MENU_HP_BARS EQU $fc
DEF SET_PAL_DEFAULT EQU $ff

; sgb palettes
; SuperPalettes indexes (see data/sgb/sgb_palettes.asm)
	const_def
	const PAL_ROUTE            ; $00
	const PAL_PALLET           ; $01
	const PAL_VIRIDIAN         ; $02
	const PAL_PEWTER           ; $03
	const PAL_CERULEAN         ; $04
	const PAL_LAVENDER         ; $05
	const PAL_VERMILION        ; $06
	const PAL_CELADON          ; $07
	const PAL_FUCHSIA          ; $08
	const PAL_CINNABAR         ; $09
	const PAL_INDIGO           ; $0A
	const PAL_SAFFRON          ; $0B
	const PAL_TOWNMAP          ; $0C
	const PAL_LOGO1            ; $0D
	const PAL_LOGO2            ; $0E
	const PAL_EXP              ; $0F
	const PAL_MEWMON           ; $10
	const PAL_BLUEMON          ; $11
	const PAL_REDMON           ; $12
	const PAL_CYANMON          ; $13
	const PAL_PURPLEMON        ; $14
	const PAL_BROWNMON         ; $15
	const PAL_GREENMON         ; $16
	const PAL_PINKMON          ; $17
	const PAL_YELLOWMON        ; $18
	const PAL_GREYMON          ; $19
	const PAL_SLOTS1           ; $1A
	const PAL_SLOTS2           ; $1B
	const PAL_SLOTS3           ; $1C
	const PAL_SLOTS4           ; $1D
	const PAL_BLACK            ; $1E
	const PAL_GREENBAR         ; $1F
	const PAL_YELLOWBAR        ; $20
	const PAL_REDBAR           ; $21
	const PAL_BADGE            ; $22
	const PAL_CAVE             ; $23
	const PAL_GAMEFREAK        ; $24
	const PAL_25               ; $25
	const PAL_26               ; $26
	const PAL_27               ; $27
	const PAL_BULBASAUR        ; $28
	const PAL_IVYSAUR          ; $29
	const PAL_CHARMANDER       ; $2A
	const PAL_CHARMELEON       ; $2B
	const PAL_CHARIZARD        ; $2C
	const PAL_SQUIRTLE         ; $2D
	const PAL_WARTORTLE        ; $2E
	const PAL_BLASTOISE        ; $2F
	const PAL_CATERPIE         ; $30
	const PAL_METAPOD          ; $31
	const PAL_BUTTERFREE       ; $32
	const PAL_WEEDLE           ; $33
	const PAL_KAKUNA           ; $34
	const PAL_PIDGEY           ; $35
	const PAL_PIDGEOTTO        ; $36
	const PAL_RATTATA          ; $37
	const PAL_RATICATE         ; $38
	const PAL_SPEAROW          ; $39
	const PAL_FEAROW           ; $3A
	const PAL_ARBOK            ; $3B
	const PAL_PIKACHU          ; $3C
	const PAL_RAICHU           ; $3D
	const PAL_SANDSHREW        ; $3E
	const PAL_NIDORAN_F        ; $3F
	const PAL_NIDOQUEEN        ; $40
	const PAL_NIDORAN_M        ; $41
	const PAL_CLEFAIRY         ; $42
	const PAL_CLEFABLE         ; $43
	const PAL_VULPIX           ; $44
	const PAL_NINETALES        ; $45
	const PAL_JIGGLYPUFF       ; $46
	const PAL_WIGGLYTUFF       ; $47
	const PAL_ZUBAT            ; $48
	const PAL_ODDISH           ; $49
	const PAL_GLOOM            ; $4A
	const PAL_VILEPLUME        ; $4B
	const PAL_PARAS            ; $4C
	const PAL_PARASECT         ; $4D
	const PAL_VENONAT          ; $4E
	const PAL_VENOMOTH         ; $4F
	const PAL_DIGLETT          ; $50
	const PAL_MEOWTH           ; $51
	const PAL_GOLDUCK          ; $52
	const PAL_MANKEY           ; $53
	const PAL_GROWLITHE        ; $54
	const PAL_POLIWAG          ; $55
	const PAL_POLIWHIRL        ; $56
	const PAL_ABRA             ; $57
	const PAL_MACHOP           ; $58
	const PAL_MACHOKE          ; $59
	const PAL_BELLSPROUT       ; $5A
	const PAL_TENTACOOL        ; $5B
	const PAL_GEODUDE          ; $5C
	const PAL_GOLEM            ; $5D
	const PAL_PONYTA           ; $5E
	const PAL_SLOWPOKE         ; $5F
	const PAL_SLOWBRO          ; $60
	const PAL_MAGNEMITE        ; $61
	const PAL_FARFETCHD        ; $62
	const PAL_DODUO            ; $63
	const PAL_SEEL             ; $64
	const PAL_DEWGONG          ; $65
	const PAL_GRIMER           ; $66
	const PAL_CLOYSTER         ; $67
	const PAL_GENGAR           ; $68
	const PAL_ONIX             ; $69
	const PAL_KRABBY           ; $6A
	const PAL_VOLTORB          ; $6B
	const PAL_EXEGGCUTE        ; $6C
	const PAL_CUBONE           ; $6D
	const PAL_HITMONLEE        ; $6E
	const PAL_HITMONCHAN       ; $6F
	const PAL_LICKITUNG        ; $70
	const PAL_WEEZING          ; $71
	const PAL_RHYHORN          ; $72
	const PAL_TANGELA          ; $73
	const PAL_HORSEA           ; $74
	const PAL_GOLDEEN          ; $75
	const PAL_STARYU           ; $76
	const PAL_STARMIE          ; $77
	const PAL_MR_MIME          ; $78
	const PAL_SCYTHER          ; $79
	const PAL_JYNX             ; $7A
	const PAL_ELECTABUZZ       ; $7B
	const PAL_MAGMAR           ; $7C
	const PAL_PINSIR           ; $7D
	const PAL_TAUROS           ; $7E
	const PAL_MAGIKARP         ; $7F
	const PAL_GYARADOS         ; $80
	const PAL_DITTO            ; $81
	const PAL_EEVEE            ; $82
	const PAL_VAPOREON         ; $83
	const PAL_FLAREON          ; $84
	const PAL_PORYGON          ; $85
	const PAL_OMANYTE          ; $86
	const PAL_KABUTOPS         ; $87
	const PAL_AERODACTYL       ; $88
	const PAL_SNORLAX          ; $89
	const PAL_DRAGONAIR        ; $8A
	const PAL_DRAGONITE        ; $8B
	const PAL_MEWTWO           ; $8C
	const PAL_MEW              ; $8D
	const PAL_YOUNGSTER        ; $8E
	const PAL_BUGCATCHER       ; $8F
	const PAL_LASS             ; $90
	const PAL_SAILOR           ; $91
	const PAL_JR_TRAINER_M     ; $92
	const PAL_JR_TRAINER_F     ; $93
	const PAL_POKEMANIAC       ; $94
	const PAL_SUPERNERD        ; $95
	const PAL_HIKER            ; $96
	const PAL_BIKER            ; $97
	const PAL_BURGLAR          ; $98
	const PAL_ENGINEER         ; $99
	const PAL_JUGGLER          ; $9A
	const PAL_FISHERMAN        ; $9B
	const PAL_SWIMMER          ; $9C
	const PAL_CUEBALL          ; $9D
	const PAL_GAMBLER          ; $9E
	const PAL_BEAUTY           ; $9F
	const PAL_PSYCHIC          ; $A0
	const PAL_ROCKER           ; $A1
	const PAL_JUGGLER2         ; $A2
	const PAL_TAMER            ; $A3
	const PAL_BIRDKEEPER       ; $A4
	const PAL_BLACKBELT        ; $A5
	const PAL_GARY1            ; $A6
	const PAL_OAK              ; $A7
	const PAL_OAKB             ; $A8
	const PAL_SCIENTIST        ; $A9
	const PAL_GIOVANNI         ; $AA
	const PAL_ROCKET           ; $AB
	const PAL_COOLTRAINER_M    ; $AC
	const PAL_COOLTRAINER_F    ; $AD
	const PAL_BRUNO            ; $AE
	const PAL_BROCK            ; $AF
	const PAL_MISTY            ; $B0
	const PAL_LT_SURGE         ; $B1
	const PAL_ERIKA            ; $B2
	const PAL_KOGA             ; $B3
	const PAL_BLAINE           ; $B4
	const PAL_SABRINA          ; $B5
	const PAL_GENTLEMAN        ; $B6
	const PAL_GARY2            ; $B7
	const PAL_GARY3            ; $B8
	const PAL_LORELEI          ; $B9
	const PAL_CHANNELER        ; $BA
	const PAL_AGATHA           ; $BB
	const PAL_LANCE            ; $BC
	const PAL_HERO             ; $BD
	const PAL_SHINY_VENUSAUR   ; $BE
	const PAL_SHINY_CHARMANDER ; $BF
	const PAL_SHINY_BLASTOISE  ; $C0
	const PAL_SHINY_CATERPIE   ; $C1
	const PAL_SHINY_METAPOD    ; $C2
	const PAL_SHINY_BUTTERFREE ; $C3
	const PAL_SHINY_KAKUNA     ; $C4
	const PAL_SHINY_PIDGEY     ; $C5
	const PAL_SHINY_PIDGEOTTO  ; $C6
	const PAL_SHINY_PIDGEOT    ; $C7
	const PAL_SHINY_RATTATA    ; $C8
	const PAL_SHINY_SPEAROW    ; $C9
	const PAL_SHINY_FEAROW     ; $CA
	const PAL_SHINY_EKANS      ; $CB
	const PAL_SHINY_ARBOK      ; $CC
	const PAL_SHINY_PIKACHU    ; $CD
	const PAL_SHINY_NIDOQUEEN  ; $CE
	const PAL_SHINY_NIDORAN_M  ; $CF
	const PAL_SHINY_CLEFAIRY   ; $D0
	const PAL_SHINY_VULPIX     ; $D1
	const PAL_SHINY_NINETALES  ; $D2
	const PAL_SHINY_JIGGLYPUFF ; $D3
	const PAL_SHINY_GOLBAT     ; $D4
	const PAL_SHINY_VILEPLUME  ; $D5
	const PAL_SHINY_PARAS      ; $D6
	const PAL_SHINY_VENONAT    ; $D7
	const PAL_SHINY_DIGLETT    ; $D8
	const PAL_SHINY_MEOWTH     ; $D9
	const PAL_SHINY_MANKEY     ; $DA
	const PAL_SHINY_PRIMEAPE   ; $DB
	const PAL_SHINY_POLIWAG    ; $DC
	const PAL_SHINY_ABRA       ; $DD
	const PAL_SHINY_MACHOKE    ; $DE
	const PAL_SHINY_WEEPINBELL ; $DF
	const PAL_SHINY_VICTREEBEL ; $E0
	const PAL_SHINY_TENTACRUEL ; $E1
	const PAL_SHINY_GRAVELER   ; $E2
	const PAL_SHINY_RAPIDASH   ; $E3
	const PAL_SHINY_MAGNETON   ; $E4
	const PAL_SHINY_DODRIO     ; $E5
	const PAL_SHINY_CHARIZARD  ; $E6
	const PAL_SHINY_MUK        ; $E7
	const PAL_SHINY_CLOYSTER   ; $E8
	const PAL_SHINY_GASTLY     ; $E9
	const PAL_SHINY_GENGAR     ; $EA
	const PAL_SHINY_HYPNO      ; $EB
	const PAL_SHINY_KINGLER    ; $EC
	const PAL_SHINY_VOLTORB    ; $ED
	const PAL_SHINY_CUBONE     ; $EE
	const PAL_SHINY_HITMONLEE  ; $EF
	const PAL_SHINY_KOFFING    ; $F0
	const PAL_SHINY_CHANSEY    ; $F1
	const PAL_SHINY_SEADRA     ; $F2
	const PAL_SHINY_GOLDEEN    ; $F3
	const PAL_SHINY_SCYTHER    ; $F4
	const PAL_SHINY_JYNX       ; $F5
	const PAL_SHINY_ELECTABUZZ ; $F6
	const PAL_SHINY_TAUROS     ; $F7
	const PAL_SHINY_GYARADOS   ; $F8
	const PAL_SHINY_VAPOREON   ; $F9
	const PAL_SHINY_DRAGONITE  ; $FA
	const PAL_SHINY_ARTICUNO   ; $FB
	const PAL_SHINY_MOLTRES    ; $FC
	const PAL_SHINY_SLOWBRO    ; $FD
	                           ; $FE
	                           ; $FF
DEF NUM_SGB_PALS EQU const_value
