RedPicFront:: INCBIN "gfx/player/red.pic"
GreenPicFront:: INCBIN "gfx/player/green.pic"
ShrinkPic1::  INCBIN "gfx/player/shrink1.pic"
ShrinkPic2::  INCBIN "gfx/player/shrink2.pic"
ShrinkPic3: INCBIN "gfx/player/shrink3.pic"
ShrinkPic1G::  INCBIN "gfx/player/shrink1g.pic"
ShrinkPic2G::  INCBIN "gfx/player/shrink2g.pic"
ShrinkPic3G: INCBIN "gfx/player/shrink3g.pic"